//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadRestaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoDetalle
    {
        public int id { get; set; }
        public int idPedido { get; set; }
        public int idMenu { get; set; }
        public int cantidad { get; set; }
        public Nullable<decimal> subtotal { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
